version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  result-storage:
    image: redis:alpine
    hostname: "redis"
    ports:
      - "6379:6379"
    volumes:
      - result-storage:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    command: -requestsQueueUrl amqp://guest:guest@rabbitmq:5672/ -resultsStorageAddr result-storage:6379
    ports:
      - "9000:9000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    command: -requestsQueueUrl amqp://guest:guest@rabbitmq:5672/ -resultsStorageAddr result-storage:6379


volumes:
  result-storage:
    driver: local