version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  result-storage:
    image: redis:alpine
    hostname: "redis"
    ports:
      - "6379:6379"
    volumes:
      - result-storage:/data

volumes:
  result-storage:
    driver: local